export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const JOBS_LOADING = 'JOBS_LOADING';
export const JOBS_FAILED = 'JOBS_FAILED';
export const ADD_JOBS = 'ADD_JOBS';

export const ADD_JOBUPDATES = 'ADD_JOBUPDATES';
export const ADD_JOBUPDATE = 'ADD_JOBUPDATE';
export const JOBUPDATES_FAILED = 'JOBUPDATES_FAILED';



export const REFDATAUSERS_LOADING = 'REFDATAUSERS_LOADING';
export const REFDATAUSERS_FAILED = 'REFDATAUSERS_FAILED';
export const ADD_REFDATAUSERS = 'ADD_REFDATAUSERS';

export const REFDATACUSTOMERS_LOADING = 'REFDATACUSTOMERS_LOADING';
export const REFDATACUSTOMERS_FAILED = 'REFDATACUSTOMERS_FAILED';
export const ADD_REFDATACUSTOMERS = 'ADD_REFDATACUSTOMERS';

export const REFDATASERVICES_LOADING = 'REFDATASERVICES_LOADING';
export const REFDATASERVICES_FAILED = 'REFDATASERVICES_FAILED';
export const ADD_REFDATASERVICES = 'ADD_REFDATASERVICES';