export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const ORDERS_LOADING = 'ORDERS_LOADING';
export const ORDERS_FAILED = 'ORDERS_FAILED';
export const ADD_ORDERS = 'ADD_ORDERS';

export const ORDERJOBS_LOADING = 'ORDERJOBS_LOADING';
export const ORDERJOBS_FAILED = 'ORDERJOBS_FAILED';
export const ADD_ORDERJOBS = 'ADD_ORDERJOBS';


export const JOBS_LOADING = 'JOBS_LOADING';
export const JOBS_FAILED = 'JOBS_FAILED';
export const ADD_JOBS = 'ADD_JOBS';

export const ADD_JOBUPDATES = 'ADD_JOBUPDATES';
export const ADD_JOBUPDATE = 'ADD_JOBUPDATE';
export const JOBUPDATES_FAILED = 'JOBUPDATES_FAILED';



export const USERMASTER_LOADING = 'USERMASTER_LOADING';
export const USERMASTER_FAILED = 'USERMASTER_FAILED';
export const ADD_USERMASTER = 'ADD_USERMASTER';

export const CUSTOMERMASTER_LOADING = 'CUSTOMERMASTER_LOADING';
export const CUSTOMERMASTER_FAILED = 'CUSTOMERMASTER_FAILED';
export const ADD_CUSTOMERMASTER = 'ADD_CUSTOMERMASTER';

export const SERVICESMASTER_LOADING = 'SERVICESMASTER_LOADING';
export const SERVICESMASTER_FAILED = 'SERVICESMASTER_FAILED';
export const ADD_SERVICESMASTER = 'ADD_SERVICESMASTER';

export const MATERIALMASTER_LOADING = 'MATERIALMASTER_LOADING';
export const MATERIALMASTER_FAILED = 'MATERIALMASTER_FAILED';
export const ADD_MATERIALMASTER = 'ADD_MATERIALMASTER';